name: Android CI
on:
  push:
    branches:
#      - $default-branch
#      - feature/ci-with-gh-actions
jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: run unit test
#      - name: run instrumental tests
#        run: ./gradlew connectedAndroidTest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build aab
        run: ./gradlew bundleRelease
