name: Release to internal testing

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Prepare keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > "${GITHUB_WORKSPACE}/keystore.jks"

      - name: Prepare keystore.properties
        run: |
          echo "keyAlias=trackme-upload" >> keystore.properties
          echo "keyPassword=${{ secrets.UPLOAD_KEY_PASSWORD }}" >> keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "storeFile=${GITHUB_WORKSPACE}/keystore.jks" >> keystore.properties

      - name: Prepare secrets.properties
        run: |
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> secrets.properties

      - name: Bump app version
        env:
          TRACKME_VERSION_NAME: ${{ github.github.ref_name }}
        run: ./gradlew bumpVersion

      - name: Commit updated version
        run: |
          git config --global user.name 'BOT'
          git config --global user.email 'bot@github.com'
          git add version.properties
          git commit -m "Automated: Bump version"

      - name: Build aab
        run: ./gradlew bundleRelease

      - name: Prepare google service account key file
        run: echo "${{ secrets.SERVICE_ACCOUNT_KEYFILE_BASE64 }}" | base64 --decode > "${GITHUB_WORKSPACE}/service_account_key.json"

      - name: Create release on google play console
        uses: johangus/android-release-action@v1
        with:
          key-file: ./service_account_key.json
          package-name: com.trackme.android
          aab-file: ./app/build/outputs/bundle/release/app-release.aab
          track: internal
          release-name: ${{ github.github.ref_name }}

      - name: Push version bump
        run: git push
