name: Release to internal testing

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
      - name: Prepare upload key
        run: |
          echo "keyAlias=${{ secrets.TEST_SECRET }}" >> keystore.properties
          cat keystore.properties
#      - name: build aab
#        run: ./gradlew bundleRelease


#      - name: Create release on google play console
#        uses: johangus/android-release-action@v1
#          with:
#            key-file: ./path/to/account-service-key-file.json
#            package-name: com.trackme.android
#            aab-file: ./app/build/outputs/bundle/release/app-release.aab
#            track: internal
#            release-name: ${{ github.event.inputs.name }}
